# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170920_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
