# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170921_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=20),
        ),
    ]
