# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170921_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
