# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170921_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='limit_spending_monthly',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
